apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: portofolio
  labels:
    name: nginx-ingress
spec:
  rules:
    - host: nginx.playrole.my.id
      http:
        paths:
          - path: /
            backend:
              serviceName: butterfly-svc
              servicePort: 80