apiVersion: apps/v1
kind: Deployment
metadata:
  name: butterfly
  namespace: portofolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: butterfly
  template:
    metadata:
      labels:
        app: butterfly
    spec:
      containers:
      - name: butterfly
        image: eryzakaria14/porto:v1
        ports:
        - containerPort: 80